version: '3'
services:
  gtfs_db:
    build: ./docker/gtfs_db
    ports:
      - "3306:3306" # host:container
    image: gtfs_db
    tty: true
    stdin_open: true
    privileged: true
    working_dir: /root/
    command: mysqld restart ; mysql -uroot -p

