version: '3'
services:
  hello_ews:
    build: ./docker/hello_ews
    ports:
      - "8080:80" # host:container
    image: hello_ews
    tty: true
    stdin_open: true
    privileged: true
    working_dir: /root/
    volumes:
      - ./public_html/hello_ews:/public_html
  ews_gui:
    build: ./docker/ews_gui
    ports:
      - "8080:80" # host:container
    image: ews_gui
    tty: true
    stdin_open: true
    privileged: true
    working_dir: /root/
    volumes:
      - ./work_dir/hello_ews/public_html:/public_html
  ews_rosenz:
    build: ./docker/ews_rosenz
    ports:
      - "8080:80" # host:container
    image: ews_rosenz
    tty: true
    stdin_open: true
    privileged: true
    working_dir: /root/
    volumes:
      - ./work_dir/ews_rosenz/public_html:/public_html
  ews_rosenz_and_multipleRange:
    build: ./docker/ews_rosenz_and_multipleRange
    ports:
      - "8080:80" # host:container
    image: ews_rosenz
    tty: true
    stdin_open: true
    privileged: true
    working_dir: /root/
    volumes:
      - ./work_dir/ews_rosenz_and_multipleRange/public_html:/public_html
